# Generated by Django 4.0.4 on 2022-07-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaron', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aaronstag',
            options={'verbose_name': "Aaron's Tag", 'verbose_name_plural': "Aaron's Tags"},
        ),
    ]
