# Generated by Django 4.0.4 on 2022-07-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('aaron', '0003_aaronpage_animateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaronpage',
            name='animateimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
