# Generated by Django 4.0.4 on 2022-07-24 14:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('aaron', '0004_alter_aaronpage_animateimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaronpage',
            name='animateimage',
        ),
        migrations.AddField(
            model_name='aaronpage',
            name='animate',
            field=wagtail.fields.StreamField([('animate', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='aaronpage',
            name='buttonimage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='.JPG Image'),
        ),
    ]
